import type { ChutesConfig } from "../config/schema.js";
import { designEffortExpected } from "../judge/types.js";
import { count } from "../text.js";
import type { Lane } from "./lane.js";
import type { PlanRecord } from "./record.js";

const LANE_TITLES: Record<Lane, string> = {
  mechanical: "Mechanical",
  judgment: "Judgment",
  redesign: "Redesign",
};

const LANE_MEANINGS: Record<Lane, string> = {
  mechanical: "Deterministic. An automated rewrite, or an engineer working from the pattern.",
  judgment: "The change is clear but the context is not. Needs somebody who knows why this exists.",
  redesign: "Should not be migrated as it stands. Migrating it faithfully preserves the problem.",
};

/**
 * Expected design effort, for ordering the Judgment listing.
 *
 * A point estimate is the right tool for a sort and the wrong one for a
 * Threshold, which is why the Lane rule uses probability mass and this uses
 * an expected value.
 */
function effortOf(record: PlanRecord): number {
  return record.answers === null ? 0 : designEffortExpected(record.answers.q5_design_effort);
}

/** Why this file landed in this Lane, in one short phrase. */
function reasonOf(record: PlanRecord): string {
  if (record.limited_by === null) return "no reason recorded";
  const confidence = record.confidence === null ? "unknown" : record.confidence.toFixed(2);
  return `${record.limited_by} (confidence ${confidence})`;
}

/** Live rows only: a file that has gone from the repository is not work. */
function live(records: PlanRecord[]): PlanRecord[] {
  return records.filter((record) => record.status !== "removed");
}

function listingFor(records: PlanRecord[], lane: Lane): PlanRecord[] {
  const inLane = live(records).filter((record) => record.lane === lane);
  // Judgment is ordered by how much design work each file needs, lowest
  // first, so the ones an agent could most plausibly draft come first. Every
  // other Lane keeps path order, and path order breaks effort ties, so the
  // document is identical across runs.
  if (lane !== "judgment") return inLane;
  return inLane.sort((a, b) => effortOf(a) - effortOf(b) || (a.path < b.path ? -1 : 1));
}

/**
 * Render the document a reviewer reads.
 *
 * Always derived from `plan.jsonl` and never the other way round: two
 * sources of truth for one Migration is how a Plan and its summary start
 * disagreeing about what work is left.
 */
export function renderMarkdown(
  records: PlanRecord[],
  config: ChutesConfig,
  migration: string,
): string {
  const lanes: Lane[] = ["mechanical", "judgment", "redesign"];
  const errors = live(records).filter((record) => record.status === "error");
  const listed = new Set<Lane>(config.report.list_files_for);

  const out: string[] = [
    `# Migration plan: ${migration}`,
    "",
    "<!-- Generated by chutes from plan.jsonl. Do not edit: the next scan overwrites it. -->",
    "",
    "Generated from `plan.jsonl`, which is the source of truth. Edit the Plan, not this file.",
    "",
    "> Classification is **not calibrated**. Treat every Lane below as a suggestion",
    "> to a reviewer, not as a decision.",
    "",
    "## Summary",
    "",
    "| Lane | Files |",
    "| --- | --- |",
  ];

  for (const lane of lanes) {
    out.push(`| ${LANE_TITLES[lane]} | ${listingFor(records, lane).length} |`);
  }
  if (errors.length > 0) {
    // Its own row, outside the Lanes, because it is not a Lane.
    out.push(`| _Not classified (error)_ | ${errors.length} |`);
  }
  const gone = records.filter((record) => record.status === "removed");
  if (gone.length > 0) out.push(`| _Removed from the repository_ | ${gone.length} |`);
  out.push("");

  for (const lane of lanes) {
    const inLane = listingFor(records, lane);
    out.push(`## ${LANE_TITLES[lane]} — ${count(inLane.length, "file")}`, "");
    out.push(`${LANE_MEANINGS[lane]}`, "");

    if (inLane.length === 0) {
      out.push("_Nothing in this Lane._", "");
      continue;
    }
    if (!listed.has(lane)) {
      out.push(
        `_Counted only. Add \`${lane}\` to \`report.list_files_for\` to list these files._`,
        "",
      );
      continue;
    }

    const shown = inLane.slice(0, config.report.max_files_per_lane);
    out.push("| File | Reason |", "| --- | --- |");
    for (const record of shown) out.push(`| \`${record.path}\` | ${reasonOf(record)} |`);
    if (shown.length < inLane.length) {
      out.push("");
      out.push(`_${inLane.length - shown.length} more, hidden by \`report.max_files_per_lane\`._`);
    }
    out.push("");
  }

  if (errors.length > 0) {
    out.push(`## Not classified — ${count(errors.length, "file")}`, "");
    out.push("These were never judged. They are **not** Judgment, and not work you can plan.", "");
    const shown = errors.slice(0, config.report.max_files_per_lane);
    out.push("| File | Error |", "| --- | --- |");
    for (const record of shown) {
      out.push(`| \`${record.path}\` | ${record.last_error ?? "unknown"} |`);
    }
    if (shown.length < errors.length) {
      out.push("");
      out.push(`_${errors.length - shown.length} more, hidden by \`report.max_files_per_lane\`._`);
    }
    out.push("");
  }

  return `${out.join("\n")}\n`;
}
